import os

class AndroidFeatures:
    """
    Injects Android-specific features like on-screen hotkeys.
    """

    def __init__(self, logger=None):
        self.logger = logger

    def log(self, message):
        if self.logger:
            self.logger.info(message)
        else:
            print(message)

    def inject_hotkeys(self, game_dir):
        """
        Creates 'android_buttons.rpy' in the game directory to add on-screen controls.
        """
        self.log("Injecting Android hotkeys...")

        file_path = os.path.join(game_dir, 'android_buttons.rpy')

        content = """
# Auto-generated by AutoModRenpy
# Adds on-screen buttons for Android navigation

init python:
    # Add the screen to the overlay so it's always visible
    config.overlay_screens.append("mobile_overlay")

screen mobile_overlay():
    zorder 100

    # Only show if not in a menu and not in a cutscene (rough check)
    if not renpy.get_screen("save") and not renpy.get_screen("preferences") and not renpy.get_screen("main_menu"):

        frame:
            background None
            xalign 1.0
            yalign 0.0
            xoffset -10
            yoffset 10

            hbox:
                spacing 20

                # Hide UI Button
                textbutton "Hide":
                    action HideInterface()
                    text_size 30
                    text_color "#ffffff99" # Semi-transparent white
                    text_outlines [(2, "#000000", 0, 0)]

                # Skip Button
                textbutton "Skip":
                    action Skip()
                    text_size 30
                    text_color "#ffffff99"
                    text_outlines [(2, "#000000", 0, 0)]

                # History/Log Button (if supported)
                textbutton "Log":
                    action ShowMenu("history")
                    text_size 30
                    text_color "#ffffff99"
                    text_outlines [(2, "#000000", 0, 0)]

                # Menu/Save Button
                textbutton "Menu":
                    action ShowMenu("save")
                    text_size 30
                    text_color "#ffffff99"
                    text_outlines [(2, "#000000", 0, 0)]

style mobile_button_text:
    size 30
    color "#ffffff"
    outlines [(2, "#000000", 0, 0)]
"""
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            self.log("Created android_buttons.rpy")
            return True
        except Exception as e:
            self.log(f"Failed to create android_buttons.rpy: {e}")
            return False
